package service

import (
	"context"

	"devops-memory-assistant/internal/ai"
	"devops-memory-assistant/internal/db"
	"devops-memory-assistant/internal/models"
)

// IncidentService handles incident related business logic.
type IncidentService struct{}

// NewIncidentService creates a new IncidentService.
func NewIncidentService() *IncidentService {
	return &IncidentService{}
}

// ExtractIncidentFromNotes extracts structured incident data from raw notes.
func (s *IncidentService) ExtractIncidentFromNotes(ctx context.Context, rawNotes string) (*models.IncidentInput, error) {
	// Use AI to extract structured data from raw notes.
	incidentInput, err := ai.ExtractIncidentFromNotes(rawNotes)
	if err != nil {
		return nil, err
	}
	// Set the raw notes in the input.
	incidentInput.RawNotes = rawNotes
	return incidentInput, nil
}

// SaveIncident saves an incident to the database.
func (s *IncidentService) SaveIncident(ctx context.Context, incidentInput *models.IncidentInput) (*models.Incident, error) {
	// Convert IncidentInput to Incident model.
	incident := models.Incident{
		Title:       incidentInput.Title,
		Summary:     incidentInput.Summary,
		Symptoms:    incidentInput.Symptoms,
		Evidence:    incidentInput.Evidence,
		RootCause:   incidentInput.RootCause,
		Resolution:  incidentInput.Resolution,
		Prevention:  incidentInput.Prevention,
		CommandsUsed: incidentInput.CommandsUsed,
		Tags:        incidentInput.Tags,
		Severity:    incidentInput.Severity,
		Environment: incidentInput.Environment,
		ServicesAffected: incidentInput.ServicesAffected,
		LessonsLearned: incidentInput.LessonsLearned,
		RawNotes:    incidentInput.RawNotes,
		// Note: Embedding will be generated by the repository layer when saving.
	}

	// Save the incident using the db package.
	id, err := db.SaveIncident(incident)
	if err != nil {
		return nil, err
	}
	incident.ID = id

	// Fetch the saved incident to get the generated fields (like timestamps, embedding).
	savedIncident, err := db.GetIncidentByID(id)
	if err != nil {
		return nil, err
	}

	return savedIncident, nil
}

// GetIncidentByID retrieves an incident by its ID.
func (s *IncidentService) GetIncidentByID(ctx context.Context, id int) (*models.Incident, error) {
	return db.GetIncidentByID(id)
}

// UpdateIncident updates an existing incident.
func (s *IncidentService) UpdateIncident(ctx context.Context, incident *models.Incident) error {
	return db.UpdateIncident(*incident)
}

// DeleteIncident deletes an incident by its ID.
func (s *IncidentService) DeleteIncident(ctx context.Context, id int) error {
	return db.DeleteIncident(id)
}

// SearchIncidents searches for incidents based on a query.
func (s *IncidentService) SearchIncidents(ctx context.Context, query string, limit int) ([]models.Incident, error) {
	return db.SearchIncidents(query, limit)
}